[tool.poetry]
name = "task3"
version = "0.1.0"
description = ""
authors = ["aboelsoud <mahmoudabooelsooud@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.2"
django-environ = "^0.9.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
